# constants/ibkr.py

# Códigos de Apertura/Cierre
CONST_IBKR_APERTURA = "O"
CONST_IBKR_CIERRE = "C"

# Códigos de Eventos de Origen
CONST_IBKR_EVENTO_EXPIRACION = "Ep"
CONST_IBKR_EVENTO_EJERCICIO = "Ex"
CONST_IBKR_EVENTO_ASSIGNMENT = "A"
CONST_IBKR_EVENTO_DEFAULT = "T"

# Listas de utilidad para validación
LIST_INDICADORES_AP_CIERRE = [CONST_IBKR_APERTURA, CONST_IBKR_CIERRE]
LIST_EVENTOS_ORIGEN_IBKR = [CONST_IBKR_EVENTO_EXPIRACION, CONST_IBKR_EVENTO_EJERCICIO, CONST_IBKR_EVENTO_ASSIGNMENT, CONST_IBKR_EVENTO_DEFAULT]

# Mapeo: Código IBKR -> Código Genérico (tb_transaccion)
# Esto actúa como un "Traductor"
MAP_IBKR_TO_GENERIC_EVENT = {
    CONST_IBKR_EVENTO_EXPIRACION: "X",  # Ep -> X
    CONST_IBKR_EVENTO_EJERCICIO: "E",    # Ex -> E
    CONST_IBKR_EVENTO_ASSIGNMENT: "A",  # A -> A
    CONST_IBKR_EVENTO_DEFAULT: "T",     # T -> T
}