from datetime import date

#database
SQLALCHEMY_DATABASE_URI = "mysql+mysqlconnector://alone:alone@localhost/bagholdercuy"

#app
SECRET_KEY = '4CE30D91FB0487BCAF5858A822D66C4C40897BB397D7D26AE651CD78BF1BB8FD'
SECURITY_PASSWORD_SALT = "****"
CLIENT_DATE_FORMAT = "%d/%m/%Y"
NUMERIC_DATE_FORMAT = "%Y%m%d"

#mail
MAIL_SERVER = "****"
MAIL_PORT = 0
MAIL_USERNAME = '****'
MAIL_PASSWORD = '****'
MAIL_USE_TLS = False
MAIL_USE_SSL = True

#General
APPNAME = ""

#ALPHAVANTAGE_KEY
ALPHAVANTAGE_KEY = ''
ALPHAVANTAGE_ENDPOINT = ''
TIINGO_KEY = ''

#IEXCLOUD
IEXCLOUD_KEY = ''
IEXCLOUD_ENDPOINT = ""

#Functions
APP_DEC_PREC = 0
TMP_DIR = ""
DEFAULT_LIMIT = 200

AUTH_SECRET_KEY = ""

#Interactive brokers
IBKR_COD_OPCION_MIN_LONGITUD = 21

#MARKETDATA
MARKETDATA_ENDPOINT = ""
MARKETDATA_API_TOKEN = ""

#FINANCIAL MODELING GREP
FINANCIAL_MODELING_GREP_ENDPOINT = ""
FINANCIAL_MODELING_GREP_API_TOKEN = ""

#Rutas
RUTA_TMP = "tmp"

# Fechas
MYSQL_MIN_DATE = date.fromisoformat("1000-01-01")
MYSQL_MAX_DATE = date.fromisoformat("9999-12-31")

# modos de insercion
WRITE_MODE_AGREGAR = 1
WRITE_MODE_REEMPLAZAR = 2
WRITE_MODE_ERROR_SI_EXISTE = 3
WRITE_MODE_IGNORAR = 4