#Tipos de transacción
TIPO_TRANS_DEPOSITO = 'D'
TIPO_TRANS_RETIRO = 'R'
TIPO_TRANS_CONVERSION = 'C'

#Tipos de Movimiento
TIPO_MOV_INGRESO = 'I'
TIPO_MOV_SALIDA = 'S'

#
IND_ACTIVO = 'S'
IND_INACTIVO = 'N'

#
PAR_OPERACION_MUL = "MUL"
PAR_OPERACION_DIV = "DIV"

#Series 
TIPO_FRECUENCIA_SERIE_DIARIA = "daily"
TIPO_FRECUENCIA_SERIE_SEMANAL = "weekly"
TIPO_FRECUENCIA_SERIE_MENSUAL = "monthly"
SERIES_PROF_CARGA_YTD = "YTD"
SERIES_PROF_CARGA_MAX = "MAX"
SERIES_PROF_CARGA_MESACTUAL = "MESACTUAL"
SERIES_PROF_CARGA_ULT3MESES = "ULT3MESES"
SERIES_PROF_CARGA_ULT6MESES = "ULT6MESES"
NUM_SEMANAS_REPROCESAR_MES = 5
SERIES_PROF_CARGA_ULT1ANYO = "ULT1ANYO"

#Reprocesar 
REPROCESO_PROF_FONDOS_TODO = "TODO"
REPROCESO_PROF_FONDOS_FCH_CIERRE = "FCH_DESDE" 